name: Deploy to Azure App Service

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Create required directories
      run: |
        mkdir -p uploads
        mkdir -p static
        mkdir -p templates
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Copy application files
      run: |
        # Copy main.py to the root for App Service deployment
        cp runs/detect/yolov8m_kitti_enhanced/weights/main.py app.py
        
    - name: Create deployment package
      run: |
        # Create a deployment package with all required files
        zip -r deployment.zip ./* -x "*.git*" -x "*.ipynb" -x "testVid/*" -x "predictions/*"
        
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: AV-Real-Time-Object-Detection
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ./deployment.zip 