name: Deploy to Azure App Service

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Create required directories
      run: |
        mkdir -p uploads
        mkdir -p static
        mkdir -p templates
        
    - name: Create deployment requirements file
      run: |
        cat > deployment-requirements.txt << EOF
        fastapi==0.104.1
        uvicorn==0.23.2
        python-multipart==0.0.6
        numpy>=1.24.0
        opencv-python-headless>=4.8.0
        torch==2.0.1
        ultralytics==8.0.196
        jinja2==3.1.2
        gunicorn==21.2.0
        pillow>=10.0.0
        EOF
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r deployment-requirements.txt
        
    - name: Prepare deployment files
      run: |
        # Copy deployment-requirements.txt to root requirements.txt
        cp deployment-requirements.txt requirements.txt
        
        # Make sure startup script is executable
        chmod +x runs/detect/yolov8m_kitti_enhanced/weights/startup.sh
        cp runs/detect/yolov8m_kitti_enhanced/weights/startup.sh .
        
        # Create .deployment file
        echo "[config]" > .deployment
        echo "SCM_DO_BUILD_DURING_DEPLOYMENT=true" >> .deployment
        echo "PYTHON_ENABLE_WORKER_EXTENSIONS=1" >> .deployment
        
    - name: Create deployment package
      run: |
        # Create a deployment package with all required files
        zip -r deployment.zip ./* -x "*.git*" -x "*.ipynb" -x "testVid/*" -x "predictions/*"
        
    - name: Deploy to Azure App Service (WebApp-Deploy)
      id: deploy-webapp
      uses: azure/webapps-deploy@v2
      continue-on-error: true
      with:
        app-name: AV-Real-Time-Object-Detection
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ./deployment.zip
        
    - name: Deploy via FTP
      if: steps.deploy-webapp.outcome == 'failure'
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: waws-prod-fra-033.ftp.azurewebsites.windows.net
        username: AV-Real-Time-Object-Detection\$AV-Real-Time-Object-Detection
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./
        server-dir: /site/wwwroot/
        exclude: |
          **/.git*
          **/.git*/**
          **/*.ipynb
          **/testVid/**
          **/predictions/** 